services:
  postgres:
    image: "postgres:latest"
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "pass"
    ports:
      - "5432:5432"
    networks:
      - db-data

  service:
    build: .
    ports:
      - "8081:8081"
    command: ./main
    depends_on:
      - postgres
    networks:
      - db-data

networks:
  db-data:
    driver: bridge
